apiVersion: v1
kind: Service
metadata:
  name: flask-portfolio-service
  labels:
    app: flask-portfolio
spec:
  type: NodePort
  selector:
    app: flask-portfolio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007   # Accessible via http://<EC2-Public-IP>:30007
